"""SQLite storage for Rectangular.

Everything lives in .rect/rect.db. Created lazily on first use (rect ui / first
insert). No init ceremony. The whole .rect/ folder is committed to git.

State model (v3):
  tickets.state = 'active' | 'done'   (the only real machine state)
  messages.action = 'close' | 'reopen' | NULL   (audit trail of state flips)
  'waiting'/'review' is DERIVED: active ticket whose last message is from a worker.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

RECT_DIR_NAME = ".rect"
DB_FILE_NAME = "rect.db"

_SCHEMA = """
CREATE TABLE IF NOT EXISTS tickets (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    title      TEXT NOT NULL,
    status     TEXT NOT NULL DEFAULT '',
    state      TEXT NOT NULL DEFAULT 'active',   -- 'active' | 'done'
    created_by TEXT NOT NULL DEFAULT 'user',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

-- The chat. A ticket IS a conversation.
-- role: user | assistant | system   (UI=user, CLI=system by default)
-- name: optional, for future multi-collab (which worker/agent)
CREATE TABLE IF NOT EXISTS messages (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    ticket_id    INTEGER NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
    role         TEXT NOT NULL DEFAULT 'system',
    name         TEXT,
    body         TEXT NOT NULL,
    status_after TEXT,                       -- status set by this message
    action       TEXT,                       -- 'close' | 'reopen' | NULL
    created_at   TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS settings (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- Full-text search. Trigram tokenizer = fuzzy substring matching for free.
-- rowid mirrors tickets.id; title + body (concatenated message bodies) are
-- kept in sync by triggers below. Triggers + table are idempotent.
CREATE VIRTUAL TABLE IF NOT EXISTS tickets_fts USING fts5(
    title, body,
    tokenize = 'trigram'
);

CREATE TRIGGER IF NOT EXISTS trg_fts_ai AFTER INSERT ON tickets BEGIN
  INSERT INTO tickets_fts(rowid, title, body) VALUES (NEW.id, NEW.title, '');
END;

CREATE TRIGGER IF NOT EXISTS trg_fts_au AFTER UPDATE OF title ON tickets BEGIN
  UPDATE tickets_fts SET title = NEW.title WHERE rowid = OLD.id;
END;

CREATE TRIGGER IF NOT EXISTS trg_fts_ad AFTER DELETE ON tickets BEGIN
  DELETE FROM tickets_fts WHERE rowid = OLD.id;
END;

-- Message changes rebuild that ticket's FTS row (body = all messages).
CREATE TRIGGER IF NOT EXISTS trg_fts_msg_ai AFTER INSERT ON messages BEGIN
  DELETE FROM tickets_fts WHERE rowid = NEW.ticket_id;
  INSERT INTO tickets_fts(rowid, title, body)
  SELECT t.id, t.title, COALESCE(
    (SELECT group_concat(m.body, ' ') FROM messages m WHERE m.ticket_id = t.id), '')
  FROM tickets t WHERE t.id = NEW.ticket_id;
END;

CREATE TRIGGER IF NOT EXISTS trg_fts_msg_au AFTER UPDATE OF body ON messages BEGIN
  DELETE FROM tickets_fts WHERE rowid = NEW.ticket_id;
  INSERT INTO tickets_fts(rowid, title, body)
  SELECT t.id, t.title, COALESCE(
    (SELECT group_concat(m.body, ' ') FROM messages m WHERE m.ticket_id = t.id), '')
  FROM tickets t WHERE t.id = NEW.ticket_id;
END;

CREATE TRIGGER IF NOT EXISTS trg_fts_msg_ad AFTER DELETE ON messages BEGIN
  DELETE FROM tickets_fts WHERE rowid = OLD.ticket_id;
  INSERT INTO tickets_fts(rowid, title, body)
  SELECT t.id, t.title, COALESCE(
    (SELECT group_concat(m.body, ' ') FROM messages m WHERE m.ticket_id = t.id), '')
  FROM tickets t WHERE t.id = OLD.ticket_id;
END;
"""


def _backfill_fts(conn: sqlite3.Connection) -> None:
    """One-time index of existing tickets for DBs created pre-search.

    FTS5 has no INSERT OR REPLACE; clear-and-rebuild is idempotent and cheap
    at this scale. Runs only when row counts diverge.
    """
    n_tickets = conn.execute("SELECT COUNT(*) FROM tickets").fetchone()[0]
    n_fts = conn.execute("SELECT COUNT(*) FROM tickets_fts").fetchone()[0]
    if n_tickets != n_fts:
        conn.execute("DELETE FROM tickets_fts")
        conn.execute(
            "INSERT INTO tickets_fts(rowid, title, body) "
            "SELECT t.id, t.title, COALESCE("
            "(SELECT group_concat(m.body, ' ') FROM messages m WHERE m.ticket_id = t.id), '') "
            "FROM tickets t"
        )
        conn.commit()


def rect_dir() -> Path:
    return Path.cwd() / RECT_DIR_NAME


def db_path() -> Path:
    return rect_dir() / DB_FILE_NAME


# Runtime junk that must NEVER land in git, even though .rect/ itself is
# committed. Written as .rect/.gitignore the moment the folder appears, so a
# fresh clone/checkout is protected even if the root .gitignore is edited.
_GITIGNORE = """\
# Auto-generated by Rectangular. Runtime state — never commit these.
ui.json
*.db-wal
*.db-shm
__pycache__/
"""


def ensure_rect_dir() -> Path:
    """Create .rect/ if needed, plus its self-guarding .gitignore."""
    d = rect_dir()
    d.mkdir(parents=True, exist_ok=True)
    gi = d / ".gitignore"
    if not gi.exists():
        gi.write_text(_GITIGNORE, encoding="utf-8")
    return d


# Schema version (informational only — schema is idempotent; no ladder).
SCHEMA_VERSION = 4


def connect() -> sqlite3.Connection:
    """Open a connection, creating .rect/ and the schema on first use.

    The schema is born-complete (idempotent CREATE IF NOT EXISTS + FTS5
    triggers), so no migration ladder is needed. The only "migration" is a
    one-time FTS backfill for DBs created before search existed.
    """
    d = ensure_rect_dir()
    conn = sqlite3.connect(d / DB_FILE_NAME)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    conn.executescript(_SCHEMA)
    _backfill_fts(conn)
    _seed_settings(conn)
    return conn


def schema_version(conn: sqlite3.Connection) -> int:
    return conn.execute("PRAGMA user_version").fetchone()[0]


def _seed_settings(conn: sqlite3.Connection) -> None:
    conn.execute(
        "INSERT OR IGNORE INTO settings (key, value) VALUES ('full_access', '0')"
    )
    conn.commit()


def get_setting(conn: sqlite3.Connection, key: str, default: str = "") -> str:
    row = conn.execute("SELECT value FROM settings WHERE key = ?", (key,)).fetchone()
    return row["value"] if row else default


def set_setting(conn: sqlite3.Connection, key: str, value: str) -> None:
    conn.execute(
        "INSERT INTO settings (key, value) VALUES (?, ?) "
        "ON CONFLICT(key) DO UPDATE SET value = excluded.value",
        (key, value),
    )
    conn.commit()


def full_access_enabled(conn: sqlite3.Connection) -> bool:
    return get_setting(conn, "full_access", "0") == "1"


def is_sqlite_db(p: Path) -> bool:
    """Cheap sanity check: sqlite files start with the 'SQLite format 3' header."""
    try:
        with p.open("rb") as f:
            return f.read(16) == b"SQLite format 3\x00"
    except OSError:
        return False
